-- MySQL Script generated by MySQL Workbench
-- Thu Jun 27 11:08:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Optica` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Optica` ;

-- -----------------------------------------------------
-- Table `Optica`.`Adreça`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`Adreça` (
  `id_adreca` INT NOT NULL,
  `carrer` VARCHAR(45) NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `pis` VARCHAR(45) NULL,
  `porta` VARCHAR(45) NULL,
  `ciutat` VARCHAR(45) NOT NULL,
  `codi_postal` TINYINT(10) NOT NULL,
  `entitat_id` INT NULL,
  `taula_entitat` ENUM('Proveidor', 'Client') NULL,
  PRIMARY KEY (`id_adreca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Proveidor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`Proveidor` (
  `id_proveidor` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(20) NULL,
  `fax` VARCHAR(20) NULL,
  `NIF` VARCHAR(45) NOT NULL,
  `adreca_id` INT NOT NULL,
  PRIMARY KEY (`id_proveidor`),
  INDEX `fk_proveidor_adreca_idx` (`adreca_id` ASC),
  CONSTRAINT `fk_proveidor_adreca`
    FOREIGN KEY (`adreca_id`)
    REFERENCES `Optica`.`Adreça` (`id_adreca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Ullera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`Ullera` (
  `id_ullera` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `graduacio_esquerra` DECIMAL(2,2) NOT NULL,
  `graduacio_dret` DECIMAL(2,2) NOT NULL,
  `tipus_montura` ENUM('flotant', 'pasta', 'metàl·lica') NOT NULL,
  `color_montura` VARCHAR(45) NOT NULL,
  `color_vidre_esquerra` VARCHAR(45) NOT NULL,
  `color_vidre_dret` VARCHAR(45) NOT NULL,
  `preu` DECIMAL(5,2) NOT NULL,
  `proveidor_id` INT NOT NULL,
  PRIMARY KEY (`id_ullera`),
  INDEX `fk_ullera_proveidor_idx` (`proveidor_id` ASC),
  CONSTRAINT `fk_ullera_proveidor`
    FOREIGN KEY (`proveidor_id`)
    REFERENCES `Optica`.`Proveidor` (`id_proveidor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`Client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `telefon` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `data_registre` DATE NOT NULL,
  `client_recomanat_id` INT NULL,
  `adreca_id` INT NOT NULL,
  PRIMARY KEY (`id_client`),
  INDEX `fk_client_client_idx` (`client_recomanat_id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_client_adreca_idx` (`adreca_id` ASC),
  CONSTRAINT `fk_client_client`
    FOREIGN KEY (`client_recomanat_id`)
    REFERENCES `Optica`.`Client` (`id_client`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_client_adreca`
    FOREIGN KEY (`adreca_id`)
    REFERENCES `Optica`.`Adreça` (`id_adreca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`Empleat` (
  `id_empleat` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `codi_postal` TINYINT NOT NULL,
  `telefon` VARCHAR(20) NULL,
  `email` VARCHAR(45) NULL,
  `Empleatcol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_empleat`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Optica`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Optica`.`Venda` (
  `id_venda` INT NOT NULL AUTO_INCREMENT,
  `data_venda` DATE NOT NULL,
  `client_id` INT NOT NULL,
  `empleat_id` INT NOT NULL,
  `ullera_id` INT NOT NULL,
  PRIMARY KEY (`id_venda`),
  INDEX `fk_venda_client_idx` (`client_id` ASC),
  INDEX `fk_venda_empleat_idx` (`empleat_id` ASC),
  INDEX `fk_venda_ullera_idx` (`ullera_id` ASC),
  CONSTRAINT `fk_venda_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `Optica`.`Client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_empleat`
    FOREIGN KEY (`empleat_id`)
    REFERENCES `Optica`.`Empleat` (`id_empleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_venda_ullera`
    FOREIGN KEY (`ullera_id`)
    REFERENCES `Optica`.`Ullera` (`id_ullera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
