-- MySQL Script generated by MySQL Workbench
-- Tue Jun 18 13:30:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Pizzeria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Pizzeria` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `Pizzeria` ;

-- -----------------------------------------------------
-- Table `Pizzeria`.`Provincia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Provincia` (
  `id_provincia` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_provincia`),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Localitat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Localitat` (
  `id_localitat` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `provincia_id` INT NOT NULL,
  PRIMARY KEY (`id_localitat`),
  INDEX `fk_localitat_provincia_idx` (`provincia_id` ASC),
  UNIQUE INDEX `nom_UNIQUE` (`nom` ASC),
  CONSTRAINT `fk_localitat_provincia`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `Pizzeria`.`Provincia` (`id_provincia`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Client`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Client` (
  `id_client` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `cognom` VARCHAR(45) NOT NULL,
  `direccio` VARCHAR(100) NOT NULL,
  `codi_postal` VARCHAR(45) NOT NULL,
  `localitat_id` INT NOT NULL,
  `provincia_id` INT NOT NULL,
  `telefon` VARCHAR(20) NULL,
  PRIMARY KEY (`id_client`),
  INDEX `fk_client_localitat_idx` (`localitat_id` ASC),
  INDEX `fk_client_provincia_idx` (`provincia_id` ASC),
  CONSTRAINT `fk_client_localitat`
    FOREIGN KEY (`localitat_id`)
    REFERENCES `Pizzeria`.`Localitat` (`id_localitat`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_client_provincia`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `Pizzeria`.`Provincia` (`id_provincia`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Botiga`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Botiga` (
  `id_botiga` INT NOT NULL AUTO_INCREMENT,
  `direccio` VARCHAR(100) NOT NULL,
  `codi_postal` VARCHAR(45) NOT NULL,
  `localitat_id` INT NOT NULL,
  `provincia_id` INT NOT NULL,
  PRIMARY KEY (`id_botiga`),
  INDEX `fk_botiga_localitat_idx` (`localitat_id` ASC),
  INDEX `fk_botiga_provincia_idx` (`provincia_id` ASC),
  CONSTRAINT `fk_botiga_localitat`
    FOREIGN KEY (`localitat_id`)
    REFERENCES `Pizzeria`.`Localitat` (`id_localitat`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_botiga_provincia`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `Pizzeria`.`Provincia` (`id_provincia`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Comanda` (
  `id_comanda` INT NOT NULL AUTO_INCREMENT,
  `data_hora` DATETIME NOT NULL,
  `tipus_comanda` ENUM('repartiment_domicili', 'recollir_botiga') NOT NULL,
  `quantitat_productes` INT NOT NULL,
  `preu_total` DECIMAL(10,2) NOT NULL,
  `client_id` INT NOT NULL,
  `botiga_id` INT NOT NULL,
  PRIMARY KEY (`id_comanda`),
  INDEX `fk_comanda_client_idx` (`client_id` ASC),
  INDEX `fk_comanda_botiga_idx` (`botiga_id` ASC),
  CONSTRAINT `fk_comanda_client`
    FOREIGN KEY (`client_id`)
    REFERENCES `Pizzeria`.`Client` (`id_client`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_comanda_botiga`
    FOREIGN KEY (`botiga_id`)
    REFERENCES `Pizzeria`.`Botiga` (`id_botiga`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Categoria_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Categoria_pizza` (
  `id_categoria_pizza` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria_pizza`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Producte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Producte` (
  `id_producte` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `descripcio` TEXT NOT NULL,
  `imatge` VARCHAR(45) NULL,
  `preu` DECIMAL(10,2) NOT NULL,
  `tipus_producte` ENUM('pizza', 'hamburguesa', 'beguda') NOT NULL,
  `categoria_pizza_id` INT NOT NULL,
  PRIMARY KEY (`id_producte`),
  INDEX `fk_producte_categoriaPizza_idx` (`categoria_pizza_id` ASC),
  UNIQUE INDEX `categoria_pizza_id_UNIQUE` (`categoria_pizza_id` ASC),
  CONSTRAINT `fk_producte_categoriaPizza`
    FOREIGN KEY (`categoria_pizza_id`)
    REFERENCES `Pizzeria`.`Categoria_pizza` (`id_categoria_pizza`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Empleat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Empleat` (
  `id_empleat` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `cognoms` VARCHAR(45) NOT NULL,
  `nif` VARCHAR(20) NOT NULL,
  `telefon` VARCHAR(20) NULL,
  `rol` ENUM('cuiner', 'repartidor') NOT NULL,
  `botiga_id` INT NOT NULL,
  PRIMARY KEY (`id_empleat`),
  INDEX `fk_empleat_botiga_idx` (`botiga_id` ASC),
  CONSTRAINT `fk_empleat_botiga`
    FOREIGN KEY (`botiga_id`)
    REFERENCES `Pizzeria`.`Botiga` (`id_botiga`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Comanda_Producte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Comanda_Producte` (
  `id_comanda_producte` INT NOT NULL AUTO_INCREMENT,
  `comanda_id` INT NOT NULL,
  `producte_id` INT NOT NULL,
  `quantitat` INT NOT NULL,
  PRIMARY KEY (`id_comanda_producte`),
  INDEX `fk_comandaProducte_comanda_idx` (`comanda_id` ASC),
  INDEX `fk_comandaProducte_producte_idx` (`producte_id` ASC),
  CONSTRAINT `fk_comandaProducte_comanda`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `Pizzeria`.`Comanda` (`id_comanda`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_comandaProducte_producte`
    FOREIGN KEY (`producte_id`)
    REFERENCES `Pizzeria`.`Producte` (`id_producte`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Pizzeria`.`Repartiment_domicili`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Pizzeria`.`Repartiment_domicili` (
  `id_repartiment` INT NOT NULL AUTO_INCREMENT,
  `comanda_id` INT NOT NULL,
  `empleat_id` INT NOT NULL,
  `data_entrega` DATETIME NOT NULL,
  PRIMARY KEY (`id_repartiment`),
  INDEX `fk_repartiment_comanda_idx` (`comanda_id` ASC),
  INDEX `fk_repartiment_empleat_idx` (`empleat_id` ASC),
  CONSTRAINT `fk_repartiment_comanda`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `Pizzeria`.`Comanda` (`id_comanda`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_repartiment_empleat`
    FOREIGN KEY (`empleat_id`)
    REFERENCES `Pizzeria`.`Empleat` (`id_empleat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
